name: Run Tests
on: push
jobs:
    php-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [7.4]
                dependency-version: [prefer-lowest, prefer-stable]
        name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install Dependencies
                run: |
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute Tests
                run: vendor/bin/phpunit

            -   name: Send Slack Notification
                uses: 8398a7/action-slack@v2
                if: failure()
                with:
                    status: ${{ job.status }}
                    author_name: ${{ github.actor }}
                env:
                    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}